import type { RecipeType } from '../Types/RecipeType';

export const mockRecipes: RecipeType[] = [
  {
    id: '1',
    name: 'Krämig Halloumigryta med linser',
    image: '',
    suitableSeasons: ['Vinter', 'Höst', 'Vår'],
    suitableWeather: {
      conditions: ['Alla'],
      temperature: { value: 5, relation: 'below' },
    },
    portions: '4-6',
    time: '45 min',
  },
  {
    id: '2',
    name: 'Fräsch Vattenmelon- & Fetasallad',
    image: '',
    suitableSeasons: ['Sommar', 'Vår'],
    suitableWeather: {
      conditions: ['Soligt', 'Vind'],
      temperature: { value: 20, relation: 'above' },
    },
    portions: '2-4',
    time: '15 min',
  },
  {
    id: '3',
    name: 'Sötpotatis-chili med mörk choklad',
    image: '',
    suitableSeasons: ['Höst', 'Vinter'],
    suitableWeather: {
      conditions: ['Molnigt', 'Regn', 'Snö', 'Vind'],
      temperature: { value: 10, relation: 'below' },
    },
    portions: '6',
    time: '60 min',
  },
  {
    id: '4',
    name: 'Zucchini- och Halloumiburgare',
    image: '',
    suitableSeasons: ['Sommar', 'Vår'],
    suitableWeather: {
      conditions: ['Soligt', 'Molnigt', 'Vind'],
      temperature: { value: 15, relation: 'above' },
    },
    portions: '4',
    time: '30 min',
  },
  {
    id: '5',
    name: 'Linssoppa med citron och spenat',
    image: '',
    suitableSeasons: ['Vår', 'Höst'],
    suitableWeather: {
      conditions: ['Molnigt', 'Regn', 'Vind'],
      temperature: { value: 15, relation: 'below' },
    },
    portions: '4',
    time: '25 min',
  },
  {
    id: '6',
    name: 'Klassisk Shakshuka',
    image: '',
    suitableSeasons: ['Alla'],
    suitableWeather: {
      conditions: ['Soligt', 'Molnigt', 'Regn', 'Vind'],
      temperature: { value: 18, relation: 'below' },
    },
    portions: '2-3',
    time: '20 min',
  },
  {
    id: '7',
    name: 'Grillad Majskolv med chilismör',
    image: '',
    suitableSeasons: ['Sommar'],
    suitableWeather: {
      conditions: ['Soligt'],
      temperature: { value: 18, relation: 'above' },
    },
    portions: '2-4',
    time: '20 min',
  },
  {
    id: '8',
    name: 'Ugnsrostad pumpasoppa med ingefära',
    image: '',
    suitableSeasons: ['Höst', 'Vinter'],
    suitableWeather: {
      conditions: ['Regn', 'Vind', 'Molnigt', 'Snö'],
      temperature: { value: 12, relation: 'below' },
    },
    portions: '4',
    time: '50 min',
  },
  {
    id: '9',
    name: 'Asiatisk nudelsallad med edamame',
    image: '',
    suitableSeasons: ['Vår', 'Sommar'],
    suitableWeather: {
      conditions: ['Soligt', 'Molnigt'],
      temperature: { value: 12, relation: 'above' },
    },
    portions: '2',
    time: '20 min',
  },
  {
    id: '10',
    name: 'Krämig Svamprisotto',
    image: '',
    suitableSeasons: ['Höst', 'Vinter'],
    suitableWeather: {
      conditions: ['Molnigt', 'Regn', 'Vind'],
      temperature: { value: 15, relation: 'below' },
    },
    portions: '4',
    time: '40 min',
  },
  {
    id: '11',
    name: 'Falafel-wrap med picklad rödlök',
    image: '',
    suitableSeasons: ['Vår', 'Sommar', 'Höst'],
    suitableWeather: {
      conditions: ['Soligt', 'Vind', 'Molnigt'],
      temperature: { value: 12, relation: 'above' },
    },
    portions: '4',
    time: '25 min',
  },
  {
    id: '12',
    name: 'Fransk Löksoppa med ostgratinerat bröd',
    image: '',
    suitableSeasons: ['Vinter'],
    suitableWeather: {
      conditions: ['Snö', 'Regn', 'Vind'],
      temperature: { value: 0, relation: 'below' },
    },
    portions: '2',
    time: '55 min',
  },
  {
    id: '13',
    name: 'Gazpacho',
    image: '',
    suitableSeasons: ['Sommar'],
    suitableWeather: {
      conditions: ['Soligt'],
      temperature: { value: 23, relation: 'above' },
    },
    portions: '4',
    time: '15 min',
  },
  {
    id: '14',
    name: 'Indisk Paneer Butter Masala',
    image: '',
    suitableSeasons: ['Vinter', 'Höst'],
    suitableWeather: {
      conditions: ['Alla'],
      temperature: { value: 10, relation: 'below' },
    },
    portions: '4',
    time: '40 min',
  },
  {
    id: '15',
    name: 'Sparris- och citronpasta',
    image: '',
    suitableSeasons: ['Vår', 'Sommar'],
    suitableWeather: {
      conditions: ['Soligt', 'Vind'],
      temperature: { value: 12, relation: 'above' },
    },
    portions: '2-4',
    time: '15 min',
  },
  {
    id: '16',
    name: 'Rödbetsburgare med chèvrekräm',
    image: '',
    suitableSeasons: ['Höst', 'Vår'],
    suitableWeather: {
      conditions: ['Molnigt', 'Vind', 'Soligt'],
      temperature: { value: 18, relation: 'below' },
    },
    portions: '4',
    time: '45 min',
  },
  {
    id: '17',
    name: 'Belugabolognese',
    image: '',
    suitableSeasons: ['Vinter', 'Höst', 'Vår'],
    suitableWeather: {
      conditions: ['Snö', 'Molnigt', 'Regn', 'Vind'],
      temperature: { value: 10, relation: 'below' },
    },
    portions: '6',
    time: '45 min',
  },
  {
    id: '18',
    name: 'Vietnamesiska vårrullar',
    image: '',
    suitableSeasons: ['Sommar', 'Vår'],
    suitableWeather: {
      conditions: ['Soligt'],
      temperature: { value: 18, relation: 'above' },
    },
    portions: '2',
    time: '40 min',
  },
  {
    id: '19',
    name: 'Ratatouille med potatis och nybakat bröd',
    image: '',
    suitableSeasons: ['Alla'],
    suitableWeather: {
      conditions: ['Molnigt', 'Regn', 'Snö', 'Vind'],
      temperature: { value: 18, relation: 'below' },
    },
    portions: '4',
    time: '20 min',
  },
  {
    id: '20',
    name: 'Ugnsbakad Blomkål med tahinisås',
    image: '',
    suitableSeasons: ['Höst', 'Vår', 'Sommar'],
    suitableWeather: {
      conditions: ['Vind', 'Molnigt'],
      temperature: { value: 15, relation: 'below' },
    },
    portions: '2-4',
    time: '40 min',
  },
];
